export const PEOPLE_GET_PENDING = 'PEOPLE_GET_PENDING';
export const PEOPLE_GET_RESOLVED = 'PEOPLE_GET_RESOLVED';
export const PEOPLE_GET_REJECTED = 'PEOPLE_GET_REJECTED';
export const STARSHIPS_GET_PENDING = 'STARSHIPS_GET_PENDING';
export const STARSHIPS_GET_RESOLVED = 'STARSHIPS_GET_RESOLVED';
export const STARSHIPS_GET_REJECTED = 'STARSHIPS_GET_REJECTED';
export const FILTER_PEOPLE = 'FILTER_PEOPLE';
